name: Deploy Azure Containers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependências
        run: dotnet restore ./PeopleRegistration.sln

      - name: Build solution
        run: dotnet build ./PeopleRegistration.sln --configuration Release --no-restore
        
  docker-build-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Definir versão da imagem
        id: version
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV
          
      - name: Build imagem Docker
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} -t ${{ env.IMAGE_NAME }}:latest .
          
      - name: Push imagem para Docker Hub
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker push ${{ env.IMAGE_NAME }}:latest
          
  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy to Azure Container Apps
        uses: azure/cli@v2
        with:
          inlineScript: |
            az containerapp update \
              --name teste-container-app \
              --resource-group teste-container-grupo-de-recurso \
              --image ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          
           
      
          
        


